document.addEventListener("DOMContentLoaded",function(){let e=e=>document.querySelector(e),t=e=>document.querySelectorAll(e),n=e(".stat-item h2");if(n){let l=parseInt(localStorage.getItem("visitorCount")||"0")+1;localStorage.setItem("visitorCount",l),n.textContent=l.toLocaleString()}let a=e("#contactForm");if(a){let s=a.querySelector(".btn"),o=["name","email","subject","message"],i=()=>{let t=o.every(t=>e(`#${t}`).value.trim());return s.disabled=!t,t};a.addEventListener("input",i),window.sendEmail=()=>{if(!i()){alert("Please fill in all fields before sending.");return}let[t,n,l,r]=o.map(t=>e(`#${t}`).value.trim()),c=`Hello Ankit,

You have received a new message from your portfolio contact form:

🔹 Name: ${t}
🔹 Email: ${n}
🔹 Subject: ${l}

📩 Message:
${r}

Best Regards,
${t}`;window.location.href=`mailto:ankitsingh10a@gmail.com?subject=${encodeURIComponent(l)}&body=${encodeURIComponent(c)}`,a.reset(),s.disabled=!0},i()}let r=window.scrollY,c=window.scrollY,d=!1;function $(){c+=(r-c)*.1,window.scrollTo(0,c),Math.abs(r-c)>.5?requestAnimationFrame($):d=!1}window.addEventListener("wheel",e=>{e.preventDefault(),r+=2*e.deltaY,r=Math.max(0,Math.min(r,document.body.scrollHeight-window.innerHeight)),d||(d=!0,requestAnimationFrame($))},{passive:!1});let u=t("section"),m=t(".sidebar nav ul li a");if(u.length>0&&m.length>0){let v=()=>{let e="",t=window.scrollY+100;u.forEach(n=>{let l=n.offsetTop,a=n.offsetHeight;t>=l&&t<l+a&&(e=n.id)}),m.forEach(t=>{let n=t.getAttribute("href").substring(1);t.classList.toggle("active",n===e)})};window.addEventListener("scroll",v),v(),m.forEach(t=>{t.addEventListener("click",n=>{n.preventDefault();let l=e(t.getAttribute("href"));l&&(r=l.offsetTop,d||(d=!0,requestAnimationFrame($)))})})}let g=e(".menu-toggle"),f=e(".sidebar");g&&f&&(g.addEventListener("click",()=>{f.classList.toggle("active"),g.classList.toggle("active")}),document.addEventListener("click",e=>{f.contains(e.target)||g.contains(e.target)||(f.classList.remove("active"),g.classList.remove("active"))}));let p=e(".back-to-top");if(p){let y=()=>{let e=window.scrollY>200;p.style.opacity=e?"1":"0",p.style.pointerEvents=e?"auto":"none"};window.addEventListener("scroll",y),p.addEventListener("click",()=>{r=0,d||(d=!0,requestAnimationFrame($))})}let b=e(".dark-mode-toggle");b&&b.addEventListener("click",()=>{document.body.classList.toggle("dark-mode");let e=b.querySelector("i"),t=b.querySelector("span");document.body.classList.contains("dark-mode")?(e.classList.replace("fa-moon","fa-sun"),t.textContent="Light Mode"):(e.classList.replace("fa-sun","fa-moon"),t.textContent="Dark Mode")}),particlesJS("particles-js",{particles:{number:{value:50,density:{enable:!0,value_area:800}},color:{value:"#b97c50"},shape:{type:"circle"},opacity:{value:.5,random:!0},size:{value:3,random:!0},move:{enable:!0,speed:2,direction:"none",random:!0}},interactivity:{detect_on:"canvas",events:{onhover:{enable:!0,mode:"repulse"},onclick:{enable:!0,mode:"push"}},modes:{repulse:{distance:100},push:{particles_nb:4}}},retina_detect:!0});let h=e(".hero");h&&(h.addEventListener("mousemove",e=>{let t=h.getBoundingClientRect(),n=(e.clientX-t.left)/t.width*100,l=(e.clientY-t.top)/t.height*100;h.style.backgroundPosition=`${n}% ${l}%`}),h.addEventListener("mouseleave",()=>{h.style.backgroundPosition="0% 50%"}));let L=t(".skill-item");L.length>0&&L.forEach((e,t)=>{e.style.opacity="0",e.style.transform="translateY(20px)",setTimeout(()=>{e.style.transition="opacity 0.5s ease-in-out, transform 0.5s ease-in-out",e.style.opacity="1",e.style.transform="translateY(0)"},100*t)})});
